export const INITIAL_FOOD_ITEMS = [
  {
    id: '1',
    name: 'Gourmet Truffle Burger',
    price: 15.99,
    description: 'Angus beef patty with black truffle aioli, caramelized onions, wild mushrooms, and melted Swiss cheese on a toasted brioche bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=600&auto=format&fit=crop',
    category: 'Burgers',
    available: true,
    prepTime: '15-20 mins',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Pepperoni Supreme Pizza',
    price: 18.49,
    description: 'Double portion of spicy pepperoni, fresh mozzarella, signature tomato sauce, and fresh basil on a hand-stretched sourdough crust.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600&auto=format&fit=crop',
    category: 'Pizza',
    available: true,
    prepTime: '20-25 mins',
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Premium Dragon Sushi Roll',
    price: 16.99,
    description: 'Shrimp tempura, cucumber inside, topped with avocado slices, unagi (eel), unagi sauce, and toasted sesame seeds.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=600&auto=format&fit=crop',
    category: 'Sushi',
    available: true,
    prepTime: '25-30 mins',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Choco-Lava Cake with Ice Cream',
    price: 8.99,
    description: 'Warm chocolate cake with a molten chocolate center, served with a scoop of premium Madagascar vanilla bean ice cream.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=600&auto=format&fit=crop',
    category: 'Desserts',
    available: true,
    prepTime: '10-12 mins',
    rating: 4.9,
  },
  {
    id: '5',
    name: 'Iced Matcha Green Tea Latte',
    price: 5.49,
    description: 'Organic Japanese ceremonial matcha whisked with oat milk and a touch of organic agave nectar over ice.',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=600&auto=format&fit=crop',
    category: 'Drinks',
    available: true,
    prepTime: '5-8 mins',
    rating: 4.6,
  },
  {
    id: '6',
    name: 'Crispy BBQ Bacon Burger',
    price: 14.99,
    description: 'Crispy applewood smoked bacon, sharp cheddar, onion rings, and smoky BBQ sauce on a toasted sesame bun.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=600&auto=format&fit=crop',
    category: 'Burgers',
    available: true,
    prepTime: '15-18 mins',
    rating: 4.5,
  },
  {
    id: '7',
    name: 'Margherita Garden Pizza',
    price: 13.99,
    description: 'Fresh roma tomatoes, buffalo mozzarella, fresh basil leaves, extra virgin olive oil, and sea salt.',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=600&auto=format&fit=crop',
    category: 'Pizza',
    available: true,
    prepTime: '15-20 mins',
    rating: 4.7,
  },
  {
    id: '8',
    name: 'Salmon Nigiri Platter',
    price: 19.99,
    description: '6 pieces of sliced premium Atlantic salmon over seasoned sushi rice balls, served with pickled ginger and fresh wasabi.',
    image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?q=80&w=600&auto=format&fit=crop',
    category: 'Sushi',
    available: false,
    prepTime: '20-25 mins',
    rating: 4.4,
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'ORD-1042',
    customerName: 'Jane Smith',
    items: 'Gourmet Truffle Burger x2, Iced Matcha Green Tea Latte x1',
    total: 37.47,
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    createdAt: '2026-06-27 08:30',
  },
  {
    id: 'ORD-1043',
    customerName: 'Michael Chang',
    items: 'Pepperoni Supreme Pizza x1, Choco-Lava Cake with Ice Cream x2',
    total: 36.47,
    paymentStatus: 'Paid',
    orderStatus: 'Processing',
    createdAt: '2026-06-27 09:15',
  },
  {
    id: 'ORD-1044',
    customerName: 'Alice Johnson',
    items: 'Premium Dragon Sushi Roll x1, Iced Matcha Green Tea Latte x2',
    total: 27.97,
    paymentStatus: 'Pending',
    orderStatus: 'Placed',
    createdAt: '2026-06-27 09:45',
  }
];

export const CATEGORIES = ['All', 'Burgers', 'Pizza', 'Sushi', 'Desserts', 'Drinks'];
export const CATEGORIES_WITH_EMOJIS = [
  { name: 'All', emoji: '🍽️' },
  { name: 'Burgers', emoji: '🍔' },
  { name: 'Pizza', emoji: '🍕' },
  { name: 'Sushi', emoji: '🍣' },
  { name: 'Desserts', emoji: '🍰' },
  { name: 'Drinks', emoji: '🥤' }
];
